spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

  application:
    name: parking-service

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false

logging:
  level:
    root: INFO
#  pattern:
#    console: ""


