apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - name: traceId
          matcherRegex: ".*\"traceId\":\"([^\"]+)\".*"
          url: "/explore?left=['now-1h','now','Loki',{\"expr\":\"{traceId=\\\"$${__value.raw}\\\"}\"}]"
        - name: userId
          matcherRegex: ".*\"userId\":\"([^\"]+)\".*"
          url: "/explore?left=['now-1h','now','Loki',{\"expr\":\"{userId=\\\"$${__value.raw}\\\"}\"}]"

